### ISSUE TITLE
关于编码规范

### ISSUE THREAD

**Issue by inkydragon** [profthecopyright/Thunder_Class#11]
这个答案提到了雷课堂还有个编码规范： [雷课堂? - 知乎](https://www.zhihu.com/question/389457315/answer/1169878318)
作业要求的 [#3.3][guid33] 和 [#5.3 代码规范分][guid53] 均提到了这点。
规范占20%也不少了。

[guid33]: 2020C++大作业“雷课堂”V2.md
[guid53]: 2020C++大作业“雷课堂”V2.md

不知道有没有同学能确认下知乎答案图片的真实性。或者发一下真正的编码规范。
回答中的我给 OCR 了一下，便于查看：[THU C++ 编码规范 · 语雀](https://www.yuque.com/woclass/cq4c11/gvy7sb)
能确认真实性我就发 .md 上来。

当然这个 repo 大家开心就好，不过还是可以搞个 `.clang-format` 文件进行自动格式化。
VSCode 和 Visual Studio 都有插件支持，其他编辑器想必也有。
合规这种事情还是自动化靠得住，人总有疏忽的地方。

----

小结一下：
目标：获得一个 `.clang-format` 文件用于自动格式化。
步骤：
- [x] 确认真正的编码规范（不然就白给了
- [x] 在  `.clang-format` 中配置规范
- [ ] 确认完成度，指出未能自动化的部分（肯定有，例如变量命名

魔改一下静态检查工具应该能做到自动化检查变量名称是否符合规范。
（实在不行 `libclang`

**Comment by profthecopyright** [comment]
Good Point! 有上课的同学补充的吗（也许是课堂上提到的代码风格规范？

**Comment by weiz0823** [comment]
与上这个课的同学确认过了。不过考虑到助教并不会有时间细致地看每一行代码，可以考虑把一些细枝末节的规则忽略，主要考虑命名等主要规则。有必要承认，里面的一部分规范能够减少出错可能性，但有一些其实只是习惯因素，要求过严。

**Comment by inkydragon** [comment]
看到知乎答案： [如何雷课堂? - 知乎](https://www.zhihu.com/question/389457315/answer/1169611271)
我也去百度了一波，然后发现了这个： [C++编码规范 - 秋阳的软件测试专栏 - IT博客](http://www.cnitblog.com/qiuyangzh/archive/2005/07/15/973.html)

这课都已经开了 15 年了么。
那么多可以直接使用的开源的编码规范不用，要用这个？

命名要求真的是有毒，这波搞得我都不想研究 libclang 了。

**Comment by profthecopyright** [comment]
> 看到知乎答案： [如何雷课堂? - 知乎](https://www.zhihu.com/question/389457315/answer/1169611271)
> 我也去百度了一波，然后发现了这个： [C++编码规范 - 秋阳的软件测试专栏 - IT博客](http://www.cnitblog.com/qiuyangzh/archive/2005/07/15/973.html)
> 
> 这课都已经开了 15 年了么。
> 那么多可以直接使用的开源的编码规范不用，要用这个？
> 
> 命名要求真的是有毒，这波搞得我都不想研究 libclang 了。

可能是为了强调教学目的吧（其实在我看来怎么着不重要，玩的就是个技能嘛
