### ISSUE TITLE
GUI是否可以考虑XAML

### ISSUE THREAD

**Issue by charlieJ107** [profthecopyright/Thunder_Class#8]
之前用过UWP, UI可以直接在VS里面拖控件, 会直接出来XAML. 到时候直接改一下属性就可以了. 微软给的文档比较齐全, 同时结合Xamarin可以实现跨平台. 如果想快速看一下Demo感受一下, 可以先自行下载Visual Studio, 然后走文档=>
https://docs.microsoft.com/zh-cn/windows/uwp/get-started/create-a-basic-windows-10-app-in-cpp
. 先做一个HelloWold感受一下基本思路, 拖一拖控件看看效果, 给自己一点正反馈的同时可以感受一下这个机制.

虽然UWP这个平台现在是半死不活, 但是它开发者友好的方面可能很适合这次的大作业.

**Comment by profthecopyright** [comment]
不错的建议
