### ISSUE TITLE
推销一个自己写的东西……

### ISSUE THREAD

**Issue by carlcc** [profthecopyright/Thunder_Class#9]
https://github.com/carlcc/Photon

设计目标是要流媒体客户端+服务端通信来着

不过目前只实现了3平台的设备查询、采集和播放。

另外要求上说的“不准用OC”，呵呵哒，MacOS的部分系统API就没法用纯C++调……

P.S.
摸鱼作品，随缘更新……在雷课堂DDL之前肯定是做不完的啦……只有已经写好的部分可以给你们用……

**Comment by profthecopyright** [comment]
感谢分享
